/// Flutter icons Pueblos
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pueblos
///      fonts:
///       - asset: fonts/Pueblos.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Pueblos {
  Pueblos._();

  static const _kFontFam = 'Pueblos';

  static const IconData doc = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calendar_full = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData bullhorn = IconData(0xe859, fontFamily: _kFontFam);
  static const IconData ticket = IconData(0xf145, fontFamily: _kFontFam);
  static const IconData newspaper = IconData(0xf1ea, fontFamily: _kFontFam);
}
